[env]
TERM = "xterm-256color"

[terminal]
osc52 = "CopyPaste"

[general]
live_config_reload = true

[window]
padding.x = 10
padding.y = 10

dynamic_padding = false

decorations = "Buttonless"

opacity = 0.9
blur = true

[font]
size = 13

[font.normal]
family = "JetBrainsMonoNL Nerd Font Mono"
style = "Medium"

[font.bold]
family = "JetBrainsMonoNL Nerd Font Mono"
style = "Heavy"

[font.bold_italic]
family = "JetBrainsMonoNL Nerd Font Mono"
style = "Heavy Italic"

[font.italic]
family = "JetBrainsMonoNL Nerd Font Mono"
style = "Medium Italic"

